<?php

namespace luis_symfonyBundle\Repository;

/**
 * EmpleadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadorRepository extends \Doctrine\ORM\EntityRepository
{
}
